### ISSUE TITLE
Maintain and display version information in the top of the makeclothes tab

### ISSUE THREAD

**Issue by joepal1976** [makehumancommunity/community-plugins-makeclothes#10]
MPFB shows a very visible version string in the top of its tab. MC should do the same, so we can ask users exactly what version they're using when they run into trouble.

At the date of releasing makehuman 1.2.0, I think we should set the version of MC to 2.0.0 (to differentiate it from the old blendertools MC).

**Comment by black-punkduck** [comment]
2.1.0 :) 

I did not change your bl_info but when you look at the method how you can put sth. into a bl_label, which is not in the \__init\__.py ... I am not really happy, but it works, see commit comment for reason (well maybe there is another solution). It is only one part of the change I did, I will do a merge request

**Comment by joepal1976** [comment]
Considering this solved.
