### ISSUE TITLE
Makeclothes2 install on Blender 3

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/community-plugins-makeclothes#17]
I seem to get an installation error when trying to install MakeClothes2 on Blender 3.0  This is Windows 11 if it matters.

![makeclosthesblender](https://user-images.githubusercontent.com/3155051/144757697-211d76da-f423-4163-9e2e-7ae68a0f60b9.png)

**Comment by goldphnx** [comment]
I cannot install on Blender 3.3.1 and 2.93.5 LTS on Ubuntustudio. I have no error messages and the add-ons menu in preferences neither changes nor shows any makeclothes option in the list. The plugin folder is visible in my .config folder for both versions of Blender. 
It does not show in the "N" menu with the other plugins such as Maketarget and MPFB.

**Comment by joepal1976** [comment]
I have now tested installing makeclothes2 from https://download.tuxfamily.org/makehuman/plugins/makeclothes2-20221230.zip from scratch in blender 3.4. So far I see no problem with it. 

Exactly which makeclothes version did you download?

If you open the preferences/addons view and write "make" in the search box (like in the image), do you see the addon appear in the list?

Can you post a screenshot of the contents of the makeclothes folder under .config?

![mc2addon](https://user-images.githubusercontent.com/10105480/210079684-c8cce363-38c0-4966-8bd4-1cd8d4800a54.png)

**Comment by NaughtyPea** [comment]
The Link You used to download the Plugin ist not available (I get a 404 Error).

If I download the Plugin directly here from GitHub I get a similar issue. The Plugin seems to be installed wihtout any mistakes (at least I get no installation error) but it's not visible in Preferences/Add-ons. So there is nothing I could select or activate

**Comment by joepal1976** [comment]
The host we've been using since the dawn of time has been having severe issues lately. I haven't managed to get all links updated, and will probably miss several of them, but there are new mirrors at:

- http://files.makehumancommunity.org/plugins/
- http://files2.makehumancommunity.org/plugins/

Download the makeclothes zip with the latest date or "latest" in its name.

**Comment by Sci-fer** [comment]
After successfully installing `makeclothes2-20240205.zip` on UPBGE 0.36.1 (Blender 3.6.2), I got the following error upon add-on activation:
> Traceback (most recent call last):
  File "C:\Program Files\blender\upbge\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\USUARIO\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\makeclothes\__init__.py", line 24, in <module>
    from .operators import *
  File "C:\Users\USUARIO\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\makeclothes\operators\__init__.py", line 6, in <module>
    from .extractclothes import MHC_OT_ExtractClothesOperator
  File "C:\Users\USUARIO\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\makeclothes\operators\extractclothes.py", line 6, in <module>
    from ..core_makeclothes_functionality import _loadMeshJson
  File "C:\Users\USUARIO\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\makeclothes\core_makeclothes_functionality.py", line 11, in <module>
    from .utils import checkMakeSkinIntegrity
  File "C:\Users\USUARIO\AppData\Roaming\UPBGE\Blender\3.6\scripts\addons\makeclothes\utils.py", line 19, in <module>
    from io_scene_obj import import_obj
ModuleNotFoundError: No module named 'io_scene_obj'

**Comment by joepal1976** [comment]
I just tested with blender 3.6.0, where it works. 

Possibly, UPBGE does not enable the legacy wavefront addon per default. Take a look in the addon preferences and make sure it is enabled:

![image](https://github.com/makehumancommunity/community-plugins-makeclothes/assets/10105480/0ba8c812-2ffd-448f-a301-92445e56e37f)

**Comment by Sci-fer** [comment]
The add-on is not even present in this version of UPBGE.

![image](https://github.com/makehumancommunity/community-plugins-makeclothes/assets/31352845/e52c8070-b3b4-4d56-849c-20829614b7f3)

Thank you

**Comment by joepal1976** [comment]
I am in the process of writing a new version of MakeClothes as a part of MPFB2, see https://github.com/makehumancommunity/mpfb2/issues/175. This will work with blender 4. 

This said, I'll see if I can find the time to do a back port of the wavefront loading code from MPFB to the standalone MakeClothes tool. That might make MakeClothes work in blender 4 too, which it currently does not.

**Comment by black-punkduck** [comment]
was fixed with 5207c78

**Comment by MangoDragonHub** [comment]
Can you update the those mirror links on the Makehuman community website? I was searching everywhere online cause the latest release doesn't work on both Blender 3.6 LTS and 4.3 either.

**Comment by joepal1976** [comment]
Which mirror links are we talking about? 

On http://www.makehumancommunity.org/content/downloads.html the link points at https://files.makehumancommunity.org/plugins/ which is the only place I know where MC2 is hosted. 

There it is also pointed out that the standalone MC2 is considered deprecated in favor of the version bundled with MPFB. The bundled version is described here: https://static.makehumancommunity.org/mpfb/docs/assets/creating_clothes.html. MPFB works with blender 4.2 and newer.

**Comment by MangoDragonHub** [comment]
It was originally was on the plugins page and it kept either linking to this Github of MakeClothes (only supporting 4.3 and newer), the zip link from download.tuxfamily and the MakeClothes 1 for Blender 2.79.

[http://www.makehumancommunity.org/content/plugins.html](http://www.makehumancommunity.org/content/plugins.html)
