### ISSUE TITLE
Blender 4.0

### ISSUE THREAD

**Issue by iGhostENT** [makehumancommunity/community-plugins-makeclothes#18]
I'm getting this error when trying to activate the addon?

ModuleNotFoundError: No module named 'io_scene_obj'

**Comment by joepal1976** [comment]
MakeClothes has not been ported to blender 4. The requested module is the wavefront addon that was current up to blender 3.6, but which has then been removed.

**Comment by black-punkduck** [comment]
well on my box it runs, I added code in december 2023 5207c78
